# Generated by Django 2.2.1 on 2019-07-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('numero_pagina', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('isbn', models.CharField(blank=True, default='', max_length=14, null=True)),
                ('data_entrada', models.DateField()),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
