# Generated by Django 2.2.1 on 2019-07-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_categoria_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='nome',
            field=models.ForeignKey(default=1, on_delete=None, parent_link=True, to='biblioteca.Categoria_livro'),
            preserve_default=False,
        ),
    ]
