# Generated by Django 2.2.1 on 2019-05-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('data_nascimento', models.CharField(max_length=14)),
                ('bi', models.CharField(max_length=20)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=20)),
                ('provincia', models.CharField(choices=[('Luanda', 'Luanda'), ('Bengo', 'Bengo'), ('Benguela', 'Benguela'), ('Bié', 'Bié'), ('Cabinda', 'Cabinda'), ('Cunene', 'Cunene'), ('Huambo', 'Huambo'), ('Huila', 'Huila'), ('Cuando kubango', 'Cuando kubango'), ('Cuanza norte', 'Cuanza norte'), ('Cuanza sul', 'Cuanza sul'), ('Lunda Norte', 'Lunda Norte'), ('Lunda sul', 'Lunda sul'), ('Malange', 'Malange'), ('Moxico', 'Moxico'), ('Namibe', 'Namibe'), ('Uige', 'Uige'), ('Zaire', 'Zaire')], max_length=20)),
                ('municipio', models.CharField(max_length=50)),
                ('residencia', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
