# Generated by Django 2.2.1 on 2019-12-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Descricao_Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=2, unique=True)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Opcao_Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_pai', models.CharField(blank=True, default='--', max_length=100, null=True)),
                ('nome_mae', models.CharField(blank=True, default='--', max_length=100, null=True)),
                ('data_nascimento', models.CharField(max_length=14)),
                ('bi', models.CharField(max_length=20)),
                ('passaporte', models.CharField(blank=True, default=' ', max_length=30, null=True)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=20)),
                ('provincia', models.CharField(choices=[('Luanda', 'Luanda'), ('Bengo', 'Bengo'), ('Benguela', 'Benguela'), ('Bié', 'Bié'), ('Cabinda', 'Cabinda'), ('Cunene', 'Cunene'), ('Huambo', 'Huambo'), ('Huila', 'Huila'), ('Cuando Cubango', 'Cuando Cubango'), ('Cuanza Norte', 'Cuanza Norte'), ('Cuanza Sul', 'Cuanza Sul'), ('Lunda Norte', 'Lunda Norte'), ('Lunda Sul', 'Lunda Sul'), ('Malanje', 'Malanje'), ('Moxico', 'Moxico'), ('Namibe', 'Namibe'), ('Uige', 'Uige'), ('Zaire', 'Zaire')], max_length=20)),
                ('municipio', models.CharField(max_length=50)),
                ('residencia', models.CharField(default='--', max_length=50, null=True)),
                ('bairro', models.CharField(default='--', max_length=80, null=True)),
                ('telefone', models.CharField(default='--', max_length=20, null=True)),
                ('email', models.EmailField(default='--', max_length=254, null=True)),
                ('estado_civil', models.CharField(choices=[('Solteiro (a)', 'solteiro (a)'), ('Casado (a)', 'casado (a)'), ('Divorciado (a)', 'Divorciado (a)')], max_length=20)),
                ('dificiencia', models.CharField(blank=True, choices=[('', ''), ('Sim', 'Sim'), ('Não', 'Não')], max_length=20, null=True)),
                ('especifica_dificiencia', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('foto', models.FileField(blank=True, default='user.jpg', null=True, upload_to='foto/')),
            ],
        ),
    ]
