# Generated by Django 2.2.1 on 2019-12-02 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Pessoa')),
                ('numero_estudante', models.CharField(max_length=10)),
                ('categoria', models.CharField(default='ESTUDANTE', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Pessoa')),
                ('numero_docente', models.CharField(max_length=10, null=True)),
                ('categoria', models.CharField(default='DOCENTE', max_length=20, null=True)),
                ('nivel_academico', models.CharField(choices=[('Licenciado', 'Licenciado'), ('Mestre', 'Mestre'), ('Doutor', 'Doutor')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Pessoa')),
                ('cargo', models.CharField(max_length=50, null=True)),
                ('categoria', models.CharField(default='FUNCIONARIO', max_length=20, null=True)),
                ('nivelacademico', models.CharField(choices=[('12ª Classe', '12ª Classe'), ('13ª Classe', '13ª Classe'), ('Têcnico Medio', 'Têcnico Médio'), ('Licenciado', 'Licenciado'), ('Mestre', 'Mestre'), ('Doutor', 'Doutor')], max_length=50)),
            ],
        ),
    ]
