# Generated by Django 2.2.1 on 2019-06-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0002_auto_20190526_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='ninel_academico',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ninel_academico',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='categoria',
            field=models.CharField(default='--', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='faculdade',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='docente',
            name='categoria',
            field=models.CharField(default='--', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='categoria',
            field=models.CharField(default='--', max_length=20, null=True),
        ),
    ]
