# Generated by Django 2.2.1 on 2019-12-02 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0002_aluno_docente_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('sigla_curso', models.CharField(default='UOR', max_length=20, null=True)),
                ('duracao', models.CharField(default=' ', max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Ano')),
                ('nome', models.CharField(default='', max_length=200)),
                ('semestre', models.CharField(choices=[('I Simestre', 'I Simestre'), ('II Simestre', 'II Simestre'), ('III Simestre', 'III Simestre'), ('IV Simestre', 'IV Simestre'), ('VI Simestre', 'VI Simestre'), ('VII Simestre', 'VII Simestre'), ('VIII Simestre', 'VIII Simestre'), ('IX Simestre', 'IX Simestre'), ('ANUAL', 'ANUAL')], max_length=200)),
                ('carga_horaria', models.CharField(default='--', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orientador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Docente')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Curso')),
                ('numero_alunos', models.CharField(default='', max_length=5)),
                ('data_limite', models.CharField(default='', max_length=20, null=True)),
            ],
        ),
    ]
