# Generated by Django 2.2.1 on 2019-06-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0003_auto_20190601_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='ninel_academico',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='categoria',
            field=models.CharField(default='ESTUDANTE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='categoria',
            field=models.CharField(default='DOCENTE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='ninel_academico',
            field=models.CharField(choices=[('Licenciado', 'Licenciado'), ('Mestre', 'Mestre'), ('Doutor', 'Doutor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='categoria',
            field=models.CharField(default='FUNCIONARIO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='ninel_academico',
            field=models.CharField(choices=[('12ªClasse', '12ª Classe'), ('13ªClasse', '13ª Classe'), ('Têcnico Medio', 'Têcnico Médio'), ('Licenciado', 'Licenciado'), ('Mestre', 'Mestre'), ('Doutor', 'Doutor')], max_length=50),
        ),
    ]
