# Generated by Django 2.2.1 on 2019-12-02 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0003_curso_disciplinas_orientador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Curso')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Aluno')),
                ('tema', models.CharField(default='', max_length=100, null=True)),
                ('opcao', models.CharField(choices=[('INDIVIDUAL', 'INDIVIDUAL'), ('GRUPO', 'GRUPO'), ('INDIVIDUAL/GRUPO', 'INDIVIDUAL / GRUPO')], max_length=20)),
                ('numero_alunos', models.CharField(blank=True, default='', max_length=3, null=True)),
                ('situacao', models.CharField(blank=True, default='Aprovado', max_length=30, null=True)),
                ('data_entrada', models.DateField()),
                ('descricao', models.TextField(blank=True, default='', max_length=1900, null=True)),
            ],
            options={
                'ordering': ['situacao'],
            },
        ),
    ]
