# Generated by Django 2.2.1 on 2019-12-02 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0004_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monografia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Aluno')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Tema')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Curso')),
                ('opcao', models.CharField(choices=[('INDIVIDUAL', 'INDIVIDUAL'), ('GRUPO', 'GRUPO'), ('INDIVIDUAL/GRUPO', 'INDIVIDUAL / GRUPO')], max_length=20)),
                ('opcao_aprovacao', models.CharField(default='Em Analise', max_length=20, null=True)),
                ('data_entrada', models.DateField()),
            ],
        ),
    ]
