# Generated by Django 2.2.1 on 2019-06-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0004_auto_20190608_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docente',
            old_name='ninel_academico',
            new_name='nivel_academico',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='ninel_academico',
            new_name='nivel_academico',
        ),
    ]
