# Generated by Django 2.2.1 on 2019-06-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0005_auto_20190608_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='nivel_academico',
            field=models.CharField(choices=[('Licenciado', 'Licenciado'), ('Mestre', 'Mestre'), ('Doutor', 'Doutor')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='numero_docente',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nivel_academico',
            field=models.CharField(choices=[('12ª Classe', '12ª Classe'), ('13ª Classe', '13ª Classe'), ('Têcnico Medio', 'Têcnico Médio'), ('Licenciado', 'Licenciado'), ('Mestre', 'Mestre'), ('Doutor', 'Doutor')], max_length=50, null=True),
        ),
    ]
