# Generated by Django 2.2.1 on 2019-12-02 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0005_monografia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defesa_Monografia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Docente')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Aluno')),
                ('monografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Monografia')),
                ('nota_final', models.CharField(default='0', max_length=2, null=True)),
                ('opcao_final', models.CharField(default='Final', max_length=20, null=True)),
                ('data_defesa', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reclamacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Curso')),
                ('motivo', models.CharField(choices=[('Falta Nota', 'Falta Nota'), ('Nota Não Lançada', 'Nota Não Lançada'), ('Propina', 'Propina'), ('Prova Não Realizada', 'Prova Não Realizada'), ('Acedio Sexual', 'Acedio Sexual'), ('Curropção', 'Curropção')], max_length=20)),
                ('data', models.DateField(auto_now_add=True, null=True)),
                ('estado', models.CharField(default='Em Analise', max_length=20, null=True)),
                ('descricao', models.CharField(default='', max_length=3000, null=True)),
            ],
        ),
    ]
