# Generated by Django 2.2.1 on 2019-06-08 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0006_auto_20190608_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='nivel_academico',
            new_name='nivelacademico',
        ),
    ]
