# Generated by Django 2.2.1 on 2019-06-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0007_auto_20190608_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=200)),
                ('sigla', models.CharField(default='UOR', max_length=20, null=True)),
                ('carga_horaria', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='docente',
            name='nivel_academico',
            field=models.CharField(choices=[('Licenciado', 'Licenciado'), ('Mestre', 'Mestre'), ('Doutor', 'Doutor')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nivelacademico',
            field=models.CharField(choices=[('12ª Classe', '12ª Classe'), ('13ª Classe', '13ª Classe'), ('Têcnico Medio', 'Têcnico Médio'), ('Licenciado', 'Licenciado'), ('Mestre', 'Mestre'), ('Doutor', 'Doutor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='municipio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='provincia',
            field=models.CharField(choices=[('Luanda', 'Luanda'), ('Bengo', 'Bengo'), ('Benguela', 'Benguela'), ('Bié', 'Bié'), ('Cabinda', 'Cabinda'), ('Cunene', 'Cunene'), ('Huambo', 'Huambo'), ('Huila', 'Huila'), ('Cuando Cubango', 'Cuando Cubango'), ('Cuanza Norte', 'Cuanza Norte'), ('Cuanza Sul', 'Cuanza Sul'), ('Lunda Norte', 'Lunda Norte'), ('Lunda Sul', 'Lunda Sul'), ('Malanje', 'Malanje'), ('Moxico', 'Moxico'), ('Namibe', 'Namibe'), ('Uige', 'Uige'), ('Zaire', 'Zaire')], max_length=20),
        ),
    ]
