# Generated by Django 2.2.1 on 2019-12-15 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0008_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinas',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Semestre'),
        ),
    ]
