# Generated by Django 2.2.1 on 2019-12-15 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0009_auto_20191215_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinas',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='disciplinas',
            name='semestre',
        ),
        migrations.AddField(
            model_name='disciplina_curso',
            name='ano',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Ano'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina_curso',
            name='semestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Semestre'),
            preserve_default=False,
        ),
    ]
