# Generated by Django 2.2.1 on 2019-06-15 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0009_curso_orientador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Disciplina')),
                ('data_realizada', models.CharField(default='', max_length=20, null=True)),
                ('data_lancamento', models.CharField(default='', max_length=20, null=True)),
            ],
        ),
    ]
