# Generated by Django 2.2.1 on 2019-06-16 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0010_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Curso')),
                ('tema', models.CharField(default='', max_length=20, null=True)),
                ('opcao', models.CharField(choices=[('INDIVIDUAL', 'INDIVIDUAL'), ('GRUPO', 'GRUPO'), ('INDIVIDUAL/GRUPO', 'INDIVIDUAL / GRUPO')], max_length=20)),
                ('numero_alunos', models.CharField(default='', max_length=10, null=True)),
                ('data_incial', models.DateField()),
                ('data_final', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='nota',
            name='data_lancamento',
            field=models.CharField(default='automatico', max_length=20, null=True),
        ),
    ]
