# Generated by Django 2.2.1 on 2019-12-15 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0010_auto_20191215_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='ano',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Ano'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='semestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Semestre'),
            preserve_default=False,
        ),
    ]
