# Generated by Django 2.2.1 on 2019-12-15 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0011_auto_20191215_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='ano_frequencia',
            new_name='ano',
        ),
        migrations.AddField(
            model_name='matricula',
            name='semestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Semestre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matricula',
            name='nota_exame',
            field=models.CharField(blank=True, default='exame', max_length=2, null=True),
        ),
    ]
