# Generated by Django 2.2.1 on 2019-06-16 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0011_auto_20190616_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta_tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Curso')),
                ('tema', models.CharField(default='', max_length=20, null=True)),
                ('opcao', models.CharField(choices=[('INDIVIDUAL', 'INDIVIDUAL'), ('GRUPO', 'GRUPO'), ('INDIVIDUAL/GRUPO', 'INDIVIDUAL / GRUPO')], max_length=20)),
                ('data_entrada', models.DateField()),
                ('estado', models.CharField(default='Espera', max_length=20, null=True)),
                ('descricao', models.CharField(default='', max_length=3000, null=True)),
            ],
        ),
    ]
