# Generated by Django 2.2.1 on 2019-06-16 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0012_proposta_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monografia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Aluno')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Tema')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Curso')),
                ('opcao', models.CharField(choices=[('INDIVIDUAL', 'INDIVIDUAL'), ('GRUPO', 'GRUPO'), ('INDIVIDUAL/GRUPO', 'INDIVIDUAL / GRUPO')], max_length=20)),
                ('opcao_aprovacao', models.CharField(default='Em Analise', max_length=20, null=True)),
                ('data_entrada', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reclamacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Curso')),
                ('opcao', models.CharField(choices=[('Falta Nota', 'Falta Nota'), ('Nota Não Lançada', 'Nota Não Lançada'), ('Propina', 'Propina'), ('Prova Não Realizada', 'Prova Não Realizada'), ('Acedio Sexual', 'Acedio Sexual'), ('Curropção', 'Curropção')], max_length=20)),
                ('data', models.DateField()),
                ('estado', models.CharField(default='Em Analise', max_length=20, null=True)),
                ('descricao', models.CharField(default='', max_length=3000, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='proposta_tema',
            old_name='estado',
            new_name='situacao',
        ),
        migrations.RenameField(
            model_name='tema',
            old_name='data_final',
            new_name='data_entrada',
        ),
        migrations.RemoveField(
            model_name='proposta_tema',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='proposta_tema',
            name='data_entrada',
        ),
        migrations.RemoveField(
            model_name='proposta_tema',
            name='opcao',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='data_incial',
        ),
        migrations.AddField(
            model_name='proposta_tema',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Aluno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tema',
            name='situacao',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proposta_tema',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Tema'),
        ),
    ]
