# Generated by Django 2.2.1 on 2019-12-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0012_auto_20191215_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='nota_exame',
            field=models.CharField(blank=True, default=' ', max_length=2, null=True),
        ),
    ]
