# Generated by Django 2.2.1 on 2019-06-16 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0013_auto_20190616_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defesa_Monografia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Docente')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Aluno')),
                ('monografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Monografia')),
                ('nota_final', models.CharField(default='0', max_length=2, null=True)),
                ('opcao_final', models.CharField(default='Final', max_length=20, null=True)),
                ('data_defesa', models.DateField()),
            ],
        ),
    ]
