# Generated by Django 2.2.1 on 2019-12-15 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0013_auto_20191215_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='numero_alunos',
        ),
    ]
