# Generated by Django 2.2.1 on 2019-06-22 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0014_defesa_monografia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chaves_Disciplina_Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Disciplina')),
            ],
        ),
        migrations.RemoveField(
            model_name='curso',
            name='disciplina',
        ),
    ]
