# Generated by Django 2.2.1 on 2019-06-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0016_auto_20190622_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='sigla',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='ano_academico',
            field=models.CharField(choices=[('1º ANO', '1º ANO'), ('2º ANO', '2º ANO'), ('3º ANO', '3º ANO'), ('4º ANO', '4º ANO'), ('5º ANO', '5º ANO')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina',
            name='semestre',
            field=models.CharField(choices=[('I Simestre', 'I Simestre'), ('II Simestre', 'II Simestre'), ('III Simestre', 'III Simestre'), ('IV Simestre', 'IV Simestre'), ('VI Simestre', 'VI Simestre'), ('VII Simestre', 'VII Simestre'), ('VIII Simestre', 'VIII Simestre'), ('IX Simestre', 'IX Simestre'), ('ANUAL', 'ANUAL')], default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.CharField(default='--', max_length=50),
        ),
    ]
