# Generated by Django 2.2.1 on 2019-06-22 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0017_auto_20190622_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamacao',
            old_name='opcao',
            new_name='motivo',
        ),
    ]
