# Generated by Django 2.2.1 on 2019-07-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0022_auto_20190701_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='numero_alunos',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='situacao',
            field=models.CharField(blank=True, default='Aprovado', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='tema',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
