# Generated by Django 2.2.1 on 2019-07-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0023_auto_20190701_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='descricao',
            field=models.TextField(blank=True, default='', max_length=1900, null=True),
        ),
    ]
