# Generated by Django 2.2.1 on 2019-07-07 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0024_tema_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Curso'),
            preserve_default=False,
        ),
    ]
